language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t christiandewitt/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true christiandewitt/docker-react npm run test